language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: O1nTy7nW7WL2nJP7UwqsPf9Wx5E41nQVhgydBHPrMQ5ytwUpxLMGAaYfGHWUrVMO0Eo6oDHsApYlNxkGGW+U1lga5JnA1SaoTY0kHYs3lUyx9kmkY4Xj1WguecN8g70oKN4O63Qn9fgV9XDWXjGN2CR+OpE8wd7mer2UqtpLYc4C4mhX3eHlWY09uzgYUXlejcqo7flP4/vXCVjWv4kAlyreIoAa2JtOh+Bj7j6FbyrH9kOSjVHXIFZ+6Ko6l/2MHdlVrvFVQbfb8hydXVeOi6VT0slC/28kP06PiKeyjMzqOLcdIjc39RZKuQ0cdNk1Ie0xkvdGzWz+iY/1XSTVZLYCDNu7kdcg6jzVmEzIg6NNIhBnfEW+2fl6QKIKHTrqs19f0Goll5zbDzY5OFk6ClSpMAQj81s2cxFapqS8xKLPXSPJsBv7OO3Rl9bs8rCp0a0TopT22QzZRrG8NyjK3hFYYaGZGmwsYuAsfyoHkVJGud2N7tSMwfpxCAxg4MJnopKyqbvijAIudOugyM+DKSo0PNLAyK3Y6/A+p37hHG6l6sjrseiCBU6jbcY1/nmwImGb5M5m3ZJG1iQKBAEfF4Ranmf7xOUvznEyDOy6tD80PEdtgHS0hgKvVrZpOjT4KKUa1MQOluaj0JxliUBkwRC8KbR6C7oQpx40iKdLm/4=
  app: test-fe-130
  on:
    repo: cs130-w21/18
    branch: fe/master
notifications:
  email:
    on_success: never
    on_failure: always
