language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: Xa1FyOCAinT1ZVOIfSvQPiVOaRJLb0vvwboH/UXRACGIVxZ7afJflzT3N7PIrWg9Mw+dBI8af8ptjjqADFDD9OaheNLc2apki53+wXs81SwNPIoi732cn2Clo8+zS2bU1nWDlV8iy4Zt5TsIeziX+f6u1Lk0tTuUy0Nx0mdLbkjuqAjnAgnDmoCxu9An+g0XrC8eoVCj9RwGNWWpqFmNXSWtWDxAjwKt6ElAyZOoeHmD86ijZRY74/IKv/t29Mx1jIGyKXxnsa9+KL2gtdD3IDaTEHQD/1ZQYShrXF5SQIt42GMsKatZzVa3lLPajo33WljbALDsii0M+5QItKnWsdp1XNlYwzRZ/ptTRb/oq/8P3M7tWg4mS3c9vrah0kCgSJV2xeJs0tlynCkKw2bCu+WHAkt3T3Uf2lgNBw35Q6C6D69QoTm2sbR4skzFFXD4Qq8nwzbugjzBHgXvpAarLUlxxo4wUJhCVGtsF9irEwMDHW4QPCzkOpvagsUT2SEuXniEox56g9nSUBOSbXme2RhedU2DNyREYk5fpRorxCNwUQk1U6LhOcWCfotPLCUq0y0ieHpgJ3JUiRZSqvSqb7YK+SoF4FUJymnLdZ+iO9Bck8LaTodnaqKD+TtpsucZLLw7Hqoo+1sPUObtVg8qg+VQHFzYiFgU9lbO+NjDDSc=
  app: test-fe-130
  on: fe/master
notifications:
  email:
    on_success: never
    on_failure: always
